// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215212039_CreateDb")]
    partial class CreateDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Data.AbcdQuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbcdQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRight")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AbcdQuestionId");

                    b.ToTable("abcd_question_answer", "questions");
                });

            modelBuilder.Entity("backend.Data.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable((string)null);

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("backend.Data.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectAbbrev")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("subject", "questions");
                });

            modelBuilder.Entity("backend.Data.AbcdQuestion", b =>
                {
                    b.HasBaseType("backend.Data.Question");

                    b.ToTable("abcd_question", "questions");
                });

            modelBuilder.Entity("backend.Data.WritingQuestion", b =>
                {
                    b.HasBaseType("backend.Data.Question");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("writing_question", "questions");
                });

            modelBuilder.Entity("backend.Data.AbcdQuestionAnswer", b =>
                {
                    b.HasOne("backend.Data.AbcdQuestion", "AbcdQuestion")
                        .WithMany("AbcdQuestionAnswers")
                        .HasForeignKey("AbcdQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbcdQuestion");
                });

            modelBuilder.Entity("backend.Data.Question", b =>
                {
                    b.HasOne("backend.Data.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("backend.Data.AbcdQuestion", b =>
                {
                    b.Navigation("AbcdQuestionAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
