// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Data.AbcdQuestionAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AbcdQuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRight")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AbcdQuestionId");

                    b.ToTable("abcd_question_answer", "questions");
                });

            modelBuilder.Entity("backend.Data.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.ToTable("question", "questions");

                    b.HasDiscriminator<int>("QuestionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SubjectAbbrev")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("subject", "subjects");
                });

            modelBuilder.Entity("backend.Entities.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("test", "tests");
                });

            modelBuilder.Entity("backend.Entities.TestQuestion", b =>
                {
                    b.Property<Guid>("TestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.HasKey("TestId", "QuestionId");

                    b.HasIndex("QuestionId");

                    b.ToTable("test_question", "tests");
                });

            modelBuilder.Entity("backend.Data.AbcdQuestion", b =>
                {
                    b.HasBaseType("backend.Data.Question");

                    b.ToTable("question", "questions");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("backend.Data.WritingQuestion", b =>
                {
                    b.HasBaseType("backend.Data.Question");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("question", "questions");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("backend.Data.AbcdQuestionAnswer", b =>
                {
                    b.HasOne("backend.Data.AbcdQuestion", "AbcdQuestion")
                        .WithMany("AbcdQuestionAnswers")
                        .HasForeignKey("AbcdQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbcdQuestion");
                });

            modelBuilder.Entity("backend.Data.Question", b =>
                {
                    b.HasOne("backend.Entities.Subject", "Subject")
                        .WithMany("Questions")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("backend.Entities.TestQuestion", b =>
                {
                    b.HasOne("backend.Data.Question", "Question")
                        .WithMany("TestQuestions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Entities.Test", "Test")
                        .WithMany("TestQuestions")
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Test");
                });

            modelBuilder.Entity("backend.Data.Question", b =>
                {
                    b.Navigation("TestQuestions");
                });

            modelBuilder.Entity("backend.Entities.Subject", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("backend.Entities.Test", b =>
                {
                    b.Navigation("TestQuestions");
                });

            modelBuilder.Entity("backend.Data.AbcdQuestion", b =>
                {
                    b.Navigation("AbcdQuestionAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
